//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C4T_Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ssmlEntries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ssmlEntries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C4T_Core.ssmlEntries", typeof(ssmlEntries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xmlns:mstts=&quot;http://www.w3.org/2001/mstts&quot; xmlns:emo=&quot;http://www.w3.org/2009/10/emotionml&quot; version=&quot;1.0&quot; xml:lang=&quot;en-US&quot;&gt;
        ///    &lt;voice name=&quot;en-US-SaraNeural&quot;&gt;
        ///        &lt;prosody rate=&quot;0%&quot; pitch=&quot;10%&quot;&gt;
        ///        &lt;lexicon uri=&quot;https://c4tai.blob.core.windows.net/c4tai/lexicon.xml&quot;/&gt;
        ///        &lt;mstts:express-as style=&quot;cheerful&quot; &gt;
        ///            You know {$chatter}, like... &lt;emphasis level=&quot;strong&quot;&gt;nya?&lt;/emphasis&gt;
        ///        &lt;/mstts:express-as&gt;
        ///       &lt;/prosody&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string catgirl {
            get {
                return ResourceManager.GetString("catgirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xmlns:mstts=&quot;http://www.w3.org/2001/mstts&quot; xmlns:emo=&quot;http://www.w3.org/2009/10/emotionml&quot; version=&quot;1.0&quot; xml:lang=&quot;en-US&quot;&gt;
        ///    &lt;voice name=&quot;en-US-SaraNeural&quot;&gt;
        ///        &lt;lexicon uri=&quot;https://c4tai.blob.core.windows.net/c4tai/lexicon.xml&quot;/&gt;
        ///        &lt;mstts:express-as style=&quot;general&quot; &gt;
        ///            I flipped a coin and got {$result}.
        ///        &lt;/mstts:express-as&gt;
        ///    &lt;/voice&gt;
        ///&lt;/speak&gt;.
        /// </summary>
        internal static string coinflip {
            get {
                return ResourceManager.GetString("coinflip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xmlns:mstts=&quot;http://www.w3.org/2001/mstts&quot; xmlns:emo=&quot;http://www.w3.org/2009/10/emotionml&quot; version=&quot;1.0&quot; xml:lang=&quot;en-US&quot;&gt;
        ///    &lt;voice name=&quot;en-US-SaraNeural&quot;&gt;
        ///        &lt;prosody rate=&quot;15%&quot; pitch=&quot;0%&quot;&gt;
        ///        &lt;lexicon uri=&quot;https://c4tai.blob.core.windows.net/c4tai/lexicon.xml&quot;/&gt;
        ///        &lt;mstts:express-as style=&quot;cheerful&quot; &gt;
        ///            Hello {follower}! Thanks for the follow!
        ///        &lt;/mstts:express-as&gt;
        ///       &lt;/prosody&gt;
        ///    &lt;/voice&gt;
        ///&lt;/speak&gt;.
        /// </summary>
        internal static string follow1 {
            get {
                return ResourceManager.GetString("follow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xmlns:mstts=&quot;http://www.w3.org/2001/mstts&quot; xmlns:emo=&quot;http://www.w3.org/2009/10/emotionml&quot; version=&quot;1.0&quot; xml:lang=&quot;en-US&quot;&gt;
        ///    &lt;voice name=&quot;en-US-SaraNeural&quot;&gt;
        ///        &lt;prosody rate=&quot;15%&quot; pitch=&quot;0%&quot;&gt;
        ///        &lt;lexicon uri=&quot;https://c4tai.blob.core.windows.net/c4tai/lexicon.xml&quot;/&gt;
        ///        &lt;mstts:express-as style=&quot;cheerful&quot; &gt;
        ///            A new follower! Hello {follower}!
        ///        &lt;/mstts:express-as&gt;
        ///       &lt;/prosody&gt;
        ///    &lt;/voice&gt;
        ///&lt;/speak&gt;.
        /// </summary>
        internal static string follow2 {
            get {
                return ResourceManager.GetString("follow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xmlns:mstts=&quot;http://www.w3.org/2001/mstts&quot; xmlns:emo=&quot;http://www.w3.org/2009/10/emotionml&quot; version=&quot;1.0&quot; xml:lang=&quot;en-US&quot;&gt;
        ///    &lt;voice name=&quot;en-US-SaraNeural&quot;&gt;
        ///        &lt;prosody rate=&quot;15%&quot; pitch=&quot;0%&quot;&gt;
        ///        &lt;lexicon uri=&quot;https://c4tai.blob.core.windows.net/c4tai/lexicon.xml&quot;/&gt;
        ///        &lt;mstts:express-as style=&quot;cheerful&quot; &gt;
        ///            Serin, say hi to {follower}!
        ///        &lt;/mstts:express-as&gt;
        ///       &lt;/prosody&gt;
        ///    &lt;/voice&gt;
        ///&lt;/speak&gt;.
        /// </summary>
        internal static string follow3 {
            get {
                return ResourceManager.GetString("follow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xmlns:mstts=&quot;http://www.w3.org/2001/mstts&quot; xmlns:emo=&quot;http://www.w3.org/2009/10/emotionml&quot; version=&quot;1.0&quot; xml:lang=&quot;en-US&quot;&gt;
        ///    &lt;voice name=&quot;en-US-SaraNeural&quot;&gt;
        ///        &lt;prosody rate=&quot;15%&quot; pitch=&quot;0%&quot;&gt;
        ///        &lt;lexicon uri=&quot;https://c4tai.blob.core.windows.net/c4tai/lexicon.xml&quot;/&gt;
        ///        &lt;mstts:express-as style=&quot;cheerful&quot; &gt;
        ///           Thanks for the follow {follower}!
        ///        &lt;/mstts:express-as&gt;
        ///       &lt;/prosody&gt;
        ///    &lt;/voice&gt;
        ///&lt;/speak&gt;.
        /// </summary>
        internal static string follow4 {
            get {
                return ResourceManager.GetString("follow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xmlns:mstts=&quot;http://www.w3.org/2001/mstts&quot; xmlns:emo=&quot;http://www.w3.org/2009/10/emotionml&quot; version=&quot;1.0&quot; xml:lang=&quot;en-US&quot;&gt;
        ///    &lt;voice name=&quot;en-US-SaraNeural&quot;&gt;
        ///        &lt;prosody rate=&quot;15%&quot; pitch=&quot;0%&quot;&gt;
        ///        &lt;lexicon uri=&quot;https://c4tai.blob.core.windows.net/c4tai/lexicon.xml&quot;/&gt;
        ///        &lt;mstts:express-as style=&quot;terrified&quot; &gt;
        ///           Serin look out! {raider} is raiding!
        ///        &lt;/mstts:express-as&gt;
        ///       &lt;/prosody&gt;
        ///    &lt;/voice&gt;
        ///&lt;/speak&gt;.
        /// </summary>
        internal static string raid1 {
            get {
                return ResourceManager.GetString("raid1", resourceCulture);
            }
        }
    }
}
